version: 2

project_name: ssl-watch

before:
  hooks:
    - go mod tidy

builds:
  - id: ssl-watch
    main: ./
    binary: ssl-watch
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE

nfpms:
  - id: packages
    package_name: ssl-watch
    ids:
      - ssl-watch
    vendor: idesyatov
    homepage: https://github.com/idesyatov/ssl-watch
    maintainer: idesyatov <noreply@github.com>
    description: Inspect and monitor TLS/SSL certificates from the command line.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin

dockers:
  - id: ssl-watch-amd64
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    use: buildx
    image_templates:
      - "ghcr.io/idesyatov/ssl-watch:{{ .Version }}-amd64"
      - "ghcr.io/idesyatov/ssl-watch:{{ .Tag }}-amd64"
      - "ghcr.io/idesyatov/ssl-watch:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.source=https://github.com/idesyatov/ssl-watch"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.licenses=MIT"
  - id: ssl-watch-arm64
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    image_templates:
      - "ghcr.io/idesyatov/ssl-watch:{{ .Version }}-arm64"
      - "ghcr.io/idesyatov/ssl-watch:{{ .Tag }}-arm64"
      - "ghcr.io/idesyatov/ssl-watch:latest-arm64"
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.source=https://github.com/idesyatov/ssl-watch"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.licenses=MIT"

docker_manifests:
  - name_template: "ghcr.io/idesyatov/ssl-watch:{{ .Version }}"
    image_templates:
      - "ghcr.io/idesyatov/ssl-watch:{{ .Version }}-amd64"
      - "ghcr.io/idesyatov/ssl-watch:{{ .Version }}-arm64"
  - name_template: "ghcr.io/idesyatov/ssl-watch:{{ .Tag }}"
    image_templates:
      - "ghcr.io/idesyatov/ssl-watch:{{ .Tag }}-amd64"
      - "ghcr.io/idesyatov/ssl-watch:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/idesyatov/ssl-watch:latest"
    image_templates:
      - "ghcr.io/idesyatov/ssl-watch:latest-amd64"
      - "ghcr.io/idesyatov/ssl-watch:latest-arm64"

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  draft: false
  prerelease: auto
